version: '3.8'

services:
  # Warstwa aplikacji (Backend)
  api:
    build: .
    container_name: cviewer_api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy  # <--- Czeka na pozytywny wynik healthchecka z bazy

  # Warstwa bazy danych (PostgreSQL)
  db:
    image: postgres:16
    container_name: cviewer_db
    restart: always
    environment:
      POSTGRES_USER: cviewer_user
      POSTGRES_PASSWORD: cviewer_password
      POSTGRES_DB: cviewer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # <--- Narzędzie pingujące bazę danych
      test: ["CMD-SHELL", "pg_isready -U cviewer_user -d cviewer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
