version: '3.8'

services:
  # Warstwa interfejsu użytkownika (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cviewer_frontend
    ports:
      - "80:80"  # Frontend będzie dostępny pod adresem http://localhost (bez portu)
    depends_on:
      - api

  # Warstwa aplikacji (FastAPI Backend)
  api:
    build: .
    container_name: cviewer_api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy

  # Warstwa bazy danych (PostgreSQL)
  db:
    image: postgres:16
    container_name: cviewer_db
    restart: always
    environment:
      POSTGRES_USER: cviewer_user
      POSTGRES_PASSWORD: cviewer_password
      POSTGRES_DB: cviewer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cviewer_user -d cviewer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
